# Generated by Django 5.1.4 on 2025-03-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0003_phoneverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="contact",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
