# Generated by Django 5.1.4 on 2025-03-24 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0002_payment_updates"),
        ("canteen_app", "0004_userprofile_contact"),
    ]

    operations = []
