# Generated by Django 5.1.4 on 2025-03-26 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0007_alter_feedback_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="feedback",
            name="food_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="canteen_app.fooditem",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together={("order", "food_item")},
        ),
    ]
