# Generated by Django 5.1.4 on 2025-03-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0008_feedback_created_at_feedback_food_item_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_time"]},
        ),
        migrations.AddField(
            model_name="order",
            name="acknowledged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Order Received"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("completed", "Completed"),
                ],
                default="received",
                max_length=20,
            ),
        ),
    ]
