# Generated by Django 5.1.4 on 2025-03-28 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0009_alter_order_options_order_acknowledged_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="status",
            new_name="order_status",
        ),
    ]
