# Generated by Django 5.1.4 on 2025-03-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0010_rename_status_order_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.RemoveField(
            model_name="order",
            name="acknowledged",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_visible",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
