# Generated by Django 5.1.4 on 2025-03-28 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0013_alter_order_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
    ]
