# Generated by Django 5.1.4 on 2025-03-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0016_order_payment_status_alter_order_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_status",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
