# Generated by Django 5.1.4 on 2025-03-28 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0018_order_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_status",
        ),
    ]
