# Generated by Django 5.1.4 on 2025-03-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0020_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="customization",
            field=models.TextField(blank=True, null=True),
        ),
    ]
