# Generated by Django 5.1.4 on 2025-04-10 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0006_add_rfid_fields"),
        ("canteen_app", "0021_cart_customization"),
    ]

    operations = []
