# Generated by Django 5.1.4 on 2025-04-21 06:57

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0023_alter_userprofile_options_userprofile_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="food_item_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="food_item_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="food_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="canteen_app.fooditem",
            ),
        ),
    ]
