# Generated by Django 5.1.4 on 2025-04-21 07:22

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0024_cart_created_at_cart_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="food_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="canteen_app.fooditem",
            ),
        ),
    ]
