# Generated by Django 5.1.4 on 2025-04-21 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen_app", "0025_cart_created_at_cart_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reset_code",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reset_code_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
